### ISSUE TITLE
[DOCS] Create getting started information for container deployments

### ISSUE THREAD

**Issue by lcawl** [elastic/stack-docs#108]
We would like to make it easier for customers to deploy the Elastic Stack on Docker and Kubernetes.  To that end, we'd like to create tutorials similar to https://www.elastic.co/guide/en/elastic-stack-overview/master/get-started-elastic-stack.html for those environments.

**Comment by lcawl** [comment]
Related to https://github.com/elastic/docs/issues/423

**Comment by jethr0null** [comment]
@lcawl If you wouldn't mind adding the Kubernetes section (in the same format as the Docker section) when you get a chance that would be much appreciated. @liztauscher will be making the changes to the website which reference this section on Nov 28th. Thank you very much!

**Comment by lcawl** [comment]
In the end we decided to have links in https://www.elastic.co/guide/en/elastic-stack-get-started/master/index.html and put any corrections in the appropriate sections of the product documentation.
