### ISSUE TITLE
role_mapping.yml breaks with upgrade to ES >= 6.3 (and removal of X-pack)

### ISSUE THREAD

**Issue by fkelbert** [elastic/stack-docs#116]
We just spent a significant amount of time figuring out why Active Directory / LDAP stops working after upgrading from ES 5.6 to ES 6.4.

The reason is:
- in ES 6.2 (with x-pack), the default path for role_mapping.yml is ES_PATH_CONF/x-pack/role_mapping.yml (see https://www.elastic.co/guide/en/elasticsearch/reference/6.2/security-settings.html)
- in ES 6.3 (no x-pack), the default path for role_mapping.yml is ES_PATH_CONF/role_mapping.yml (see https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html)

We did not find any explicit documentation of this change, even though it did actually break functionality.
In particular, also the Interactive Upgrade Guide should highlight these and similar required changes.

**Comment by lcawl** [comment]
This information now exists in the breaking changes here: https://www.elastic.co/guide/en/elasticsearch/reference/6.3/breaking-changes-6.3.html#breaking_63_packaging_changes

**Comment by fkelbert** [comment]
Hi @lcawl ,

This looks great, thank you.

One thing: Both [https://www.elastic.co/guide/en/elastic-stack-overview/6.3/trb-security-path.html](https://www.elastic.co/guide/en/elastic-stack-overview/6.3/trb-security-path.html) and [https://www.elastic.co/guide/en/elasticsearch/reference/6.3/breaking-changes-6.3.html#breaking_63_packaging_changes](https://www.elastic.co/guide/en/elasticsearch/reference/6.3/breaking-changes-6.3.html#breaking_63_packaging_changes) mention `log4js.properties`. In my installation, however, I can only find file `log4j2.properties`.

**Comment by lcawl** [comment]
Good catch!  I've created https://github.com/elastic/stack-docs/pull/129

**Comment by lcawl** [comment]
The file name is fixed in both locations now
