### ISSUE TITLE
Possible incorrect certificate ref in elastic-docker-tls.yml

### ISSUE THREAD

**Issue by ArpitKotecha** [elastic/stack-docs#1223]
Isn't `- xpack.security.http.ssl.certificate` in es03 should ref to `$CERTS_DIR/es03/es03.crt` instead of `$CERTS_DIR/es02/es02.crt 
`
https://github.com/elastic/stack-docs/blob/20473bfd9e9e01ffe408c6cd28b87438d0fdf5bf/docs/en/getting-started/docker/elastic-docker-tls.yml#L74-L89

**Comment by gtback** [comment]
Fixed by #1225 , I think

**Comment by ArpitKotecha** [comment]
Yup #1225 should fix this

**Comment by gtback** [comment]
Closing since #1225 was merged
