### ISSUE TITLE
{ref} attribute not defined?

### ISSUE THREAD

**Issue by lucascosti** [elastic/stack-docs#130]
Looking at the current published version of the terminology list in the glossary (https://www.elastic.co/guide/en/elastic-stack-glossary/current/terms.html), there are multiple instances of incomplete links being rendered:

For example:

> This value can be overridden by specifying a routing value at index time, or a /mapping-routing-field.html[routing field] in the mapping.

After examining the source, it seems that the `{ref}` attribute is not defined, which is breaking the declaration of the links.

**Comment by lcawl** [comment]
Thanks for catching this!  You can see the fixes now here: 
https://www.elastic.co/guide/en/elastic-stack-glossary/current/terms.html
