### ISSUE TITLE
Tactical doc updates for our products in Docker / Kubernetes 

### ISSUE THREAD

**Issue by DanRoscigno** [elastic/stack-docs#140]
In order to improve the getting started experience for our users that deploy with Docker or Kubernetes we need some updates / changes to the docs.  Target date for this is 30 November 2018.

**Docker** config files and commands in [GitHub](https://github.com/DanRoscigno/Beats-container-configs): 
- [x] Filebeat
- [x] Metricbeat
- [x] Heartbeat
- [x] Packetbeat
- [x] Auditbeat
- [x] Elasticsearch
- [x] Kibana

Updates to these docs for **Docker** will be tracked here:
- [x] Filebeat
- [x] Metricbeat
- [x] Heartbeat
- [x] Packetbeat
- [x] Auditbeat
~- [ ] Elasticsearch~ No change needed
~- [ ] Kibana~ No change needed

Updates to these docs for **Kubernetes** will be tracked here:
- [x] Filebeat
- [x] Metricbeat
~- [ ] Heartbeat~ : not supported yet
~- [ ] Packetbeat~ : not supported yet
~- [ ] Auditbeat~ : not supported yet

~Other docs that will be updated through the Helm project~ (later, not part of this issue):
~- [ ] Elasticsearch~
~- [ ] Kibana~
~- [ ] APM Server~

PRs in:
-[x] Beats
~-[ ] Elasticsearch~ No change needed
~-[ ] Kibana~ No change needed

cc: @liztauscher @kate-smith 

@tylerjl @exekias Can you volunteer someone to help review? Similar to the blogs and demos I have been running past you, our goal here is to publish good advice in the docs, and we don't want to embarrass ourselves by publishing something that works but is deprecated.

**Comment by tylerjl** [comment]
@DanRoscigno yep, happy to look over any updates. Also /cc @Crazybus here for visibility re: Helm documentation.

**Comment by exekias** [comment]
Sure @DanRoscigno, count me in!

**Comment by DanRoscigno** [comment]
Links:

getting started [thoughts](https://docs.google.com/document/d/1iG-w2_gbtNDbW4W5eOWU-_b9Q6rCsXVsD963_Zq24L8/edit)

**Comment by kate-smith** [comment]
Checking in here - is Nov 30 still the target date here? I want to make sure it is on the calendar for Web Team. Thank you!

**Comment by dedemorton** [comment]
@DanRoscigno  Nov 30 is kind of aggressive for me. I'm still wrapping up some 6.5 work and the Thanksgiving holiday is looming. It kind of depends on how far you will carry the football down the field before handing it off to me. :-) :-)

**Comment by kate-smith** [comment]
@jethr0null & @DanRoscigno - thoughts on the timeline here?

**Comment by jethr0null** [comment]
It isn't obvious to me that any updates have been made looking at the history here (I could well be missing something) @DanRoscigno are you able to provide a status update here for all of the checklist items you've outlined (the Helm ones excluded given that we're not making any updates until the charts are actually announced)?

**Comment by kate-smith** [comment]
@DanRoscigno - any update here? Hoping to get an idea of where we stand before meeting today - thank you!

**Comment by DanRoscigno** [comment]
@kate-smith , as we discussed a couple weeks ago, this work starts today.  I questioned having a status meeting on the first day of the project when you scheduled it.

**Comment by kate-smith** [comment]
@DanRoscigno - an update here would be great - thank you! I will reschedule a check in for later in the week. The preliminary deadline I have from my notes includes:

- Initial updates & quick fix → this can happen quickly post-6.5 (Week of Nov 26 - 30)
- Updates done Nov 28 → Stack/docs repo GH ticket (Dan to open)
- Web to post live Nov 29 / Nov 30 → Web ticket for downloads page

Is this timeline still reasonable? The date in the main ticket (Nov 30) above is for the web work, so the update on docs is due Nov 28.

**Comment by DanRoscigno** [comment]
What is web posting on Nov 29/30?  Are they updating elastic.co/start, or some other page?  I have been concentrating on the documentation changes.

**Comment by kate-smith** [comment]
The update in the short-term are the download pages associated with the list in the main ticket. Long-term plan is to overall update all download pages.

cc @liztauscher 

An updated timeline from Dan includes:

1) Technical fixes to docs: Dan, Tyler, Carlos.  Finish writing the fixes this week, have them reviewed by Tyler and Carlos week of December 3rd
2) Deb publish docs changes (Exact date TBC at the moment)
3) write updates to the web pages (one example, https://www.elastic.co/downloads/kibana).  Probably start on Monday Dec 3rd --> Kate & Liz will be making any content changes / edits to relevant download pages
4) Publish the new web pages

**Comment by DanRoscigno** [comment]
initial Docker configs in [GitHub](https://github.com/DanRoscigno/Beats-container-configs)
(I could not deal with Google Docs breaking configs with silly "smart" quotes).  Will work on the rest and switch to 6.5.0.

**Comment by DanRoscigno** [comment]
@tylerjl @exekias 

Can you please have a look at the configs in [GitHub](https://github.com/DanRoscigno/Beats-container-configs)

File structure in the README.

I have done my testing on Docker for Mac, with Elasticsearch and Kibana running in Docker also.

I will work on the docs that wrap around the configs, and then the same for Kubernetes.

**Comment by tylerjl** [comment]
Thanks @DanRoscigno - I ran through the steps on Fedora and it all seemed to work pretty well.

- I assume that there'll eventually be documentation about trying out the hinting vs. annotation setups, etc. since the filebeat/metricbeat bash scripts have commands to try both configs. At the moment running those steps fails to run the same container invocation since `filebeat`/`metricbeat` are already claimed.
- This is probably only an issue for native Linux users, so I don't expect it would be a big issue, but metricbeat complains about config permissions on metricbeat.yml and won't start without `chown root` and `chmod go-w` on the configuration file.

Aside from that all the containers came up and the dashboards had useful metrics :+1:

**Comment by DanRoscigno** [comment]
Thanks Tyler.  Yup, working on the docs next.  I will fix the permissions when it gets put into wherever the docs folks keep files for download (which maybe is in github/elastic/beats, I will check).

The sh files will not be downloadable, they will be in code blocks in the docs, so the second filebeat/metricbeat won't fail like what you saw.

Did you look at the commands?  Anything embarrassing in there?  I never used Docker (without Kubernetes) before other than that last thing you looked at for me)

Thanks again @tylerjl

**Comment by tylerjl** [comment]
Nope, all the `docker` commands look pretty sane. I think it serves as a good example of how to run things :ship:

**Comment by DanRoscigno** [comment]
Doc pages to link to from product download pages:

Docker:
 [Filebeat](https://www.elastic.co/guide/en/beats/filebeat/current/running-on-docker.html)
 [Metricbeat](https://www.elastic.co/guide/en/beats/metricbeat/current/running-on-docker.html)
 [Heartbeat](https://www.elastic.co/guide/en/beats/heartbeat/current/running-on-docker.html)
 [Packetbeat](https://www.elastic.co/guide/en/beats/packetbeat/current/running-on-docker.html)
 [Auditbeat](https://www.elastic.co/guide/en/beats/auditbeat/current/running-on-docker.html)
 [Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html)
 [Kibana](https://www.elastic.co/guide/en/kibana/current/docker.html)

Kubernetes:
[Filebeat](https://www.elastic.co/guide/en/beats/filebeat/current/running-on-kubernetes.html)
[Metricbeat](https://www.elastic.co/guide/en/beats/metricbeat/current/running-on-kubernetes.html)

**Comment by DanRoscigno** [comment]
@tylerjl @exekias 
What do you think about using a short lived setup pod like [this](https://github.com/DanRoscigno/Beats-container-configs/blob/master/Kubernetes/configs/packetbeat-setup.yaml) to setup the dashboards, ML jobs, index pattern, etc?  Similar to what I did for Docker, run the setup separate from the pod that processes data.

**Comment by DanRoscigno** [comment]
@debadair For the Beats Running in Docker documentation pages I need to be able to specify a different run command for each Beat (there are flags that differ on each one).  Is there an example of how to customize the asciidoc section shown below for each Beat?
![image](https://user-images.githubusercontent.com/25182304/49232621-49abc900-f3c2-11e8-879d-17fb7627739a.png)

**Comment by dedemorton** [comment]
Yes you can use conditional blocks. Let me know if you need help with the coding. Looks ok from skimming.

**Comment by dedemorton** [comment]
Note that you cannot use the conditions within the example blocks so you will need a separate block for each command as you show above.

**Comment by DanRoscigno** [comment]
Docs are updated in my fork, I have to go through the other pages (hopefully just the install pages) and link to the Docker / Kubernetes pages instead of telling people to pull the images.

Support question is worked out for Beats, @acchen97 is looking into the public facing support matrix, and engineering / janitors are updating the internal support wiki.  We are good to go for Metricbeat and Filebeat for Kubernetes (I crossed out the rest up top)

**Comment by DanRoscigno** [comment]
Replaced docker pull commands on Beats install pages with links to the docker instructions.

**Comment by DanRoscigno** [comment]
I found the *beat-docker.yml files in the root dir of each Beat @exekias , I am going to use those instead of mine since they are already there.  So, I am just adding the docker run command to do the setup (dashboards etc.), fixing the run commands for processing the data, and linking to the Docker / Kubernetes pages from the Getting Started/install pages (replacing the docker pull command on the install page).

**Comment by exekias** [comment]
> @tylerjl @exekias
> What do you think about using a short lived setup pod like [this](https://github.com/DanRoscigno/Beats-container-configs/blob/master/Kubernetes/configs/packetbeat-setup.yaml) to setup the dashboards, ML jobs, index pattern, etc? Similar to what I did for Docker, run the setup separate from the pod that processes data.

:+1: this is what I use in my demos: https://github.com/exekias/beats-kubernetes-demo/blob/master/kubernetes/metricbeat-daemonset.yaml#L288-L350

**Comment by DanRoscigno** [comment]
To Do (Dan)
- [ ] Double check the Elasticsearch Docker docs (I believe they are good)
- [ ] Double check the Kibana Docker docs (I believe they are good)
- [ ] Submit PR to Beats repo
- [ ] Submit PR to Elasticsearch repo (if needed, I doubt it)
- [ ] Submit PR to Kibana repo (if needed, I doubt it)

**Comment by DanRoscigno** [comment]
@liztauscher : @jethr0null and I met after Kate's call.  We are good to go with links from the product downloads to the docs for the Docker and Kubernetes lists up top (the checkboxes).  PM, Infra, Support, and Engineering need to work out the details for adding links for Helm charts and new Docker / Kubernetes / OpenShift, etc. in the future.  This will happen later.

@dedemorton : I expect the PR to go in on Monday, I think I am done but need to test things one more time on Monday.  Once you and engineering look at the PR (assuming it is accepted), can you let @kate-smith know so she can plan with the web team to make the links from the Download pages to the Docker and Kubernetes docs pages?

**Comment by DanRoscigno** [comment]
PR failed, I had edited two YAML files that are auto generated, tomorrow I will edit the source files and then DeDe will try generating the files.  Close!

**Comment by DanRoscigno** [comment]
PR is merged. I will check the docs in a few hours.

**Comment by kate-smith** [comment]
@DanRoscigno - everything set here? Webteam is ready to push the Docker & Kubernetes update live with the Helm Chart push at 8AM PT.

CC @liztauscher

**Comment by DanRoscigno** [comment]
Good to go.
