### ISSUE TITLE
SQL JDBC Plugin Example Typo

### ISSUE THREAD

**Issue by sgelastic** [elastic/stack-docs#147]
Example at the bottom of [this page](https://www.elastic.co/guide/en/elasticsearch/reference/6.4/sql-jdbc.html), shows text as:
```
jdbc:es://http://server:3456/timezone=UTC&page.size=250
```
Correct text is:
```
jdbc:es://http://server:3456?timezone=UTC&page.size=250
```

**Comment by jrodewig** [comment]
This has been corrected in the currently maintained versions of the docs:
https://www.elastic.co/guide/en/elasticsearch/reference/7.11/sql-jdbc.html#_additional

Thanks for raising this!
