### ISSUE TITLE
[404 not found]  Well, that about wraps it up for this page

### ISSUE THREAD

**Issue by jihyunjeongme** [elastic/stack-docs#1698]
Hello elastic ML team,

I've found that the link, `Getting started -> To get started with Machine Learning please have a look at` is 404 not found.
- https://www.elastic.co/guide/en/elastic-stack-overview/current/ml-getting-started.htm

![image](https://user-images.githubusercontent.com/43984584/121805127-bdfa9f00-cc84-11eb-802f-14d3fd28c3ad.png)

Could you check the link?

Best,
Jihyun Jeong

**Comment by sophiec20** [comment]
Transferring to docs repo.

Latest Getting Started pages can be found here https://www.elastic.co/guide/en/machine-learning/current/ml-getting-started.html

The stack overview pages are listed as legacy documentation and we stopped contributing to these in 7.4; however does this page require redirects? @lcawl

**Comment by lcawl** [comment]
@jihyunjeongme Thanks for contacting us! If possible, can you tell me how you reached that URL? That content doesn't exist in the "Stack Overview" even going back to its beginning (version 6.3), so if there are out-dated links in the documentation, I haven't succeeded in finding them.

**Comment by jihyunjeongme** [comment]
@lcawl Thank you for the quick response!

I found that the link, here, `https://github.com/elastic/ml-cpp` > `Getting started -> To get started with Machine Learning please have a look at`
![image](https://user-images.githubusercontent.com/43984584/122202850-65234480-ced8-11eb-81f6-c8021b5ae15d.png)

**Comment by lcawl** [comment]
Thank you very much!  I've created https://github.com/elastic/ml-cpp/pull/1915 to fix all those musty links
