### ISSUE TITLE
Anomaly detection documentation reorganization

### ISSUE THREAD

**Issue by lcawl** [elastic/stack-docs#1739]
## Goal

Related to https://github.com/elastic/stack-docs/issues/1725

The goal of this issue is to track the effort of creating a new, more user-friendly structure for the anomaly detection documentation.

### Reorganized TOC

Anomaly detection
* ~~Detecting anomalies ...~~ [#1747](https://github.com/elastic/stack-docs/pull/1747), [#1750](https://github.com/elastic/stack-docs/pull/1750), [#1753](https://github.com/elastic/stack-docs/pull/1753)
  * Split into concrete tasks https://github.com/elastic/stack-docs/pull/1943 
* Advanced concepts [#1731](https://github.com/elastic/stack-docs/pull/1731)
* API quick reference
* Resources [#1731](https://github.com/elastic/stack-docs/pull/1731), [#74802](https://github.com/elastic/elasticsearch/pull/74802)

Link fixes:
* https://github.com/elastic/elasticsearch/pull/74942
* https://github.com/elastic/elasticsearch/pull/74943
* https://github.com/elastic/kibana/pull/104350
* https://github.com/elastic/security-docs/pull/782
* https://github.com/elastic/stack-docs/pull/1751
* https://github.com/elastic/stack-docs/pull/1752
* https://github.com/elastic/kibana/pull/105011
* https://github.com/elastic/elasticsearch/pull/75194
* https://github.com/elastic/security-docs/pull/801

**Comment by szabosteve** [comment]
I close it in favor of https://github.com/elastic/ml-team/issues/838.
