### ISSUE TITLE
Update getting started to show data ingestion through Elastic Agent

### ISSUE THREAD

**Issue by dedemorton** [elastic/stack-docs#1884]
If we keep the [stack getting started docs](https://www.elastic.co/guide/en/elastic-stack-get-started/7.16/get-started-elastic-stack.html) in 8.0, we need to update the data ingestion parts to show Elastic Agent rather than Metricbeat.

I know there are other initiatives underway, but I want to make sure these docs get updated if they stick around.

For 7.16, we should at the very least add a pointer to the observability docs where we cover how to use Elastic Agent to ingest logs/metrics/apm/etc.

**Comment by ollyhowell** [comment]
FYI the stack getting started guide has been EOL'd for 8.3: - https://github.com/elastic/tech-content/issues/152
