### ISSUE TITLE
 Is the description「Elasticsearch 8.0.0-alpha1」correct?

### ISSUE THREAD

**Issue by taku333** [elastic/stack-docs#208]
Is the description「Elasticsearch 8.0.0-alpha1」correct?
master branch So is there no problem?

![image](https://user-images.githubusercontent.com/16697482/52641988-767d7000-2f1d-11e9-92e7-5b4d50b1ece7.png)
https://www.elastic.co/guide/en/elastic-stack/master/upgrading-elastic-stack.html

**Comment by lcawl** [comment]
Yes, that information comes from https://raw.githubusercontent.com/elastic/elasticsearch/master/docs/Versions.asciidoc

**Comment by taku333** [comment]
@lcawl 
Thanks information!!
I have no problem, I will close.
