### ISSUE TITLE
[ML] Anomaly detection alert screenshots are out of date

### ISSUE THREAD

**Issue by jgowdyelastic** [elastic/stack-docs#2214]
The screenshots on [this page](https://www.elastic.co/guide/en/machine-learning/8.1/ml-configuring-alerts.html#creating-anomaly-jobs-health-rules) show an earlier version of the feature which supported multiple job selection.
This is now not allowed and so the screenshots should be updated to avoid confusion.

**Comment by szabosteve** [comment]
I opened https://github.com/elastic/elasticsearch/pull/89532 to update the screenshot.

**Comment by szabosteve** [comment]
Fixed via https://github.com/elastic/elasticsearch/pull/89532
