### ISSUE TITLE
Elastic Azure Links Redirect to ERROR URLs

### ISSUE THREAD

**Issue by sylvie777** [elastic/stack-docs#2327]
From @lisatrosh (original post: https://github.com/elastic/website-requests/issues/997)

Provide the following information to help us identify and troubleshoot the issue.
- Page error URL: https://www.elastic.co/guide/en/elastic-stack-deploy/current/azure-marketplace.html
- Page error URL: https://www.elastic.co/guide/en/elastic-stack-deploy/current/azure-marketplace-getting-started.html

![Image 2-9-23 at 3 23 PM](https://user-images.githubusercontent.com/114245362/217945459-abef03b4-015a-43e9-8898-1b4d99e7dd05.jpeg)

- Device type: Browser
- Specifics (e.g., OS, Hardware, Browser, etc.):

List out steps on how to recreate the issue.

1. When I google elastic azure marketplace:

See screenshot attached of top 2 links redirecting to the wrong link. Correct link is: https://azuremarketplace.microsoft.com/en-us/marketplace/apps/elastic.ec-azure-pp?exp=ubp8&tab=Overview 

If you have a screenshot, add it below.

**Comment by dustyjackson** [comment]
@sylvie777 What is the status of this ticket, please?

**Comment by sylvie777** [comment]
@dustyjackson Please check with the Stack Docs team. I transferred this out of my [repo](https://github.com/elastic/website-requests/issues/997) because my team does not manage the Docs section.

**Comment by dustyjackson** [comment]
@lisatrosh FYI above

**Comment by lisatrosh** [comment]
Hello @sylvie777 how do we reach the stack docs team and is this ticket already transferred? Do they use Github? cc. @dustyjackson

**Comment by sylvie777** [comment]
@lisatrosh You're currently in their repo: https://github.com/elastic/stack-docs/issues/2327 😄

**Comment by kilfoyle** [comment]
Hi @sylvie777 and @lisatrosh 
Let me know if I misunderstand, but it seems to me that the links are correct as is. That is, [Elasticsearch (Self managed)](https://azuremarketplace.microsoft.com/en-US/marketplace/apps/elastic.elasticsearch) and [Elastic Cloud (Elasticsearch Service) ](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/elastic.ec-azure-pp?exp=ubp8&tab=Overview) are distinct products both available in Azure Marketplace.

We are, however, checking on the Elastic Self Managed product in Azure to find out if there are plans underway to deprecate it.

**Comment by dustyjackson** [comment]
@kilfoyle I would welcome the chance to discuss this live on a call and explain my concerns about the links and where they are pointing to. Please let me know if we can do that. Thank you.

**Comment by kilfoyle** [comment]
Thanks @dustyjackson! I added something to your calendar for Thursday. @sylvie777 it'd be really nice if you can attend to, as I really am not familiar with the redirect process. 

I am wondering if we should instead put a link at the top of those docs pages recommending people toward the Elasticsearch Service product in Azure Marketplace, but let's discuss that in the call.

**Comment by kilfoyle** [comment]
@dustyjackson As we discussed, the main pages of the [Azure Marketplace docs](https://www.elastic.co/guide/en/elastic-stack-deploy/current/azure-marketplace.html) are updated now. Here's how the notice appears:

![Screenshot 2023-03-06 at 12 20 15 PM](https://user-images.githubusercontent.com/41695641/223184137-2b0c08b5-7d2b-44b0-bc85-d0858ad21bca.png)

Separately, we're [adding a "no index" tag](https://github.com/elastic/docs/pull/2626) to this section of the docs, so in time that should help reduce their prominence in the Google search results. 

I think this issue can be closed now, but if we've missed anything please let us know.
