### ISSUE TITLE
Elasticsearch Documentation: "_doc" or "doc"

### ISSUE THREAD

**Issue by sylvie777** [elastic/stack-docs#236]
A user contacted us through the "Contact Us" form and wrote:

>>>
In the documentation it says to use “_doc” for a query in the following page: 

https://www.elastic.co/guide/en/elasticsearch/reference/6.3/docs-update.html

I’ve been fiddling around with a 6.3 installation, and in my experiences only ```doc``` works. The documentation changed in 6.1 to 6.2 to specify ```_doc```. 
<<<

**Comment by ppf2** [comment]
`_doc` should work (this assumes that the document they are trying to update was originally created with `_doc` as the document type).  If only `doc` works for them, this suggests that the document they are trying to update was originally created with the document type set to `doc`.  If they have further questions on this topic, feel free to refer them to https://discuss.elastic.co/c/elasticsearch :)

**Comment by sylvie777** [comment]
Thanks, @ppf2! I'll pass this along.
