### ISSUE TITLE
List ports and routes required for Stack deployment

### ISSUE THREAD

**Issue by jrodewig** [elastic/stack-docs#2431]
**Problem**
Users need to understand which ports and network routes need to be available to design a Stack deployment. Right now, this information is scattered across several Stack guides.

**Comment by liladler** [comment]
Thanks for this @jrodewig. 

It'd be great to have this documented so open source & paying customers would have an centralised starting point, as they'd be able to self serve. 
A crucial point to this as well would be a reference architecture, combining all of our components (beats/agent/kibana/fleet/es etc)

**Comment by jhmass** [comment]
This has been requested quite often. It would be great if this was available. Please also include ports related to orchestration features like ECE and ECK. Where appropriate?

Thanks!

**Comment by jamesagarside** [comment]
Glad to see this. It will seriously speed up the journey for people evaluating Elastic.

**Comment by liladler** [comment]
@jrodewig hi, is there any update on this? 
This is still being asked for by users & customers and would be great to be able to share a centralised view on our architecture.

**Comment by karenzone** [comment]
This is not the destination, but is a start: https://github.com/elastic/ingest-docs/issues/197

**Comment by jrodewig** [comment]
Hi @liladler!

Sharing details from our offline convo: This is in our backlog, but we've got some other important work that's prioritized ahead of it. I can't guarantee a publish date, but we'll try to fit it in soon. 

Thanks again for raising this. Please continue to surface requests like this to the docs team. It's really valuable.

**Comment by jrodewig** [comment]
I opened https://github.com/elastic/stack-docs/pull/2531 as a stopgap to cover the major components. We'll need to do some follow-up PRs to cover ECE/ECK ports as well as linking to the settings. However, I think this is better than nothing for now.

**Comment by jrodewig** [comment]
Some feedback from https://github.com/elastic/stack-docs/pull/2531:

**Ingest architectures**
 - The reference architecture focuses on ingest so only shows breakdown of ingest components. Would be great to have a reference architecture that presents Elasticsearch components, such as ML nodes, Hot, Cold, Frozen buckets etc.
 
 **Cloud**
 - The page references APM/fleet server. In the Cloud console we still call it integration server. might worth a clarification that it refers to the same component?
 - We're referencing cloud, but cloud ports are different (uses TLS).
 
 These were out of scope for the PR, but we should look to address them later on.
