### ISSUE TITLE
[ML] Clarify E5 built-in NLP model offline  installation

### ISSUE THREAD

**Issue by jeanfabrice** [elastic/stack-docs#2665]
The E5 built-in NLP model page in https://www.elastic.co/guide/en/machine-learning/current/ml-nlp-e5.html simply has a link to the [eland client documentation](https://www.elastic.co/guide/en/elasticsearch/client/eland/current/machine-learning.html#ml-nlp-pytorch-air-gapped) when it comes to install the E5 model in [air-gapped environment](https://www.elastic.co/guide/en/machine-learning/current/ml-nlp-e5.html#air-gapped-install-e5)

The problem is that the [Eland page for offline installation](https://www.elastic.co/guide/en/elasticsearch/client/eland/current/machine-learning.html#ml-nlp-pytorch-air-gapped) uses [bert-base-NER](https://huggingface.co/dslim/bert-base-NER) as an example

From a customer perspective who is going to install the E5 model in an air-gapped environment following the documentation, it is not very straightforward what Huggingface Git repo has to be used to install the E5 model. The reference to `multilingual-e5-small` and `multilingual-e5-small-optimized` at the [top of the documentation page](https://www.elastic.co/guide/en/machine-learning/current/ml-nlp-e5.html#ml-nlp-e5) is not really helpful IMO.

Should we clarify / explicitly mention that:
- `multilingual-e5-small` model is hosted on Git repo https://huggingface.co/elastic/multilingual-e5-small, which itself references https://huggingface.co/intfloat/multilingual-e5-small  
- `multilingual-e5-small-optimized` model is hosted on Git repo https://huggingface.co/elastic/multilingual-e5-small-optimized

The second issue is that the `Eland client` page, which uses `bert-base-NER` as an example, suggests using `--task-type ner.`
This does not work for the E5 model. The autodetection does not work either:
```
elasticsearch.BadRequestError: BadRequestError(400, 'x_content_parse_exception', '[ner] only allows IOB tokenization tagging for classification labels; provided [LABEL_0, LABEL_1]')
```

It looks like the E5 model requires to use the forcefully `--task-type text_embedding` command line option.
Should we add that also as an important note in the [Eland page](https://www.elastic.co/guide/en/elasticsearch/client/eland/current/machine-learning.html#ml-nlp-pytorch-air-gapped): 
> When using eland to import the built-in E5 NLP model, use `--task-type text_embedding`

**Comment by davidkyle** [comment]
There is a problem with the optimised model `multilingual-e5-small-optimized` it cannot be loaded from the cloned git repository. There is a long [slack thread](https://elastic.slack.com/archives/G013E0SNF3M/p1708681834866049) about the problem but basically the `pytorch_model.bin` cannot be loaded which must be done to convert the model to the format used by Elasticsearch.

The only option for `multilingual-e5-small-optimized` is to download the pre-prepared files in the right format from https://ml-models.elastic.co/ and follow the air gapped install guide here: https://www.elastic.co/guide/en/machine-learning/master/ml-nlp-elser.html#air-gapped-install

**Comment by szabosteve** [comment]
I'm working on adding the instructions to the E5 conceptual docs page.

**Comment by szabosteve** [comment]
I've added the available air-gapped install methods to the E5 page. I'm closing this issue now. Thanks for the work everyone!
