### ISSUE TITLE
[Docs] - minor typo in docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc

### ISSUE THREAD

**Issue by jamie-wilson88** [elastic/stack-docs#2869]
Minor typo in:
docs/en/stack/ml/nlp/ml-nlp-elser.asciidoc
https://www.elastic.co/guide/en/machine-learning/current/ml-nlp-elser.html

"Using the traned models API in Dev Console"
Should be:
"Using the trained models API in Dev Console"

**Comment by kosabogi** [comment]
Related PR: https://github.com/elastic/stack-docs/pull/2871
