### ISSUE TITLE
Upgrade guide from 5.0-5.5 mentions Upgrade Assistant

### ISSUE THREAD

**Issue by kostasb** [elastic/stack-docs#37]
Following the interactive upgrade guide https://www.elastic.co/products/upgrade_guide

Repro:

> -What version of Elasticsearch are you currently running?
5.0-5.5
-Are you running in Elastic Cloud?
No
-Which products are you using with Elasticsearch?
Kibana
-Do you use X-Pack?
Yes
... next steps irrelevant 
-Jump straight to 6.0

The resulting steps now mention using the [Upgrade Assistant](https://www.elastic.co/guide/en/kibana/5.6/xpack-upgrade-assistant.html) which is a Kibana 5.6 feature. Nowhere in the process is deploying a Kibana 5.6 node, or upgrading Kibana to 5.6 is mentioned.

![image](https://user-images.githubusercontent.com/15780449/37037775-b243bd0e-215b-11e8-9e1d-28c251ecc559.png)

In this case I believe the [xpack migration API](https://www.elastic.co/guide/en/elastic-stack/current/upgrading-elastic-stack.html#upgrade-internal-indices) should be referenced instead of the upgrade assistant, with steps to upgrade the .kibana and .security indices after installing Elasticsearch 6.0+ (which means starting Elasticsearch 6 with the old .kibana and .security indices? That's how we seem to mention in the docs - haven't tested this path myself yet)

**Comment by debadair** [comment]
Fixed.
