### ISSUE TITLE
Release notes should point to release blogs

### ISSUE THREAD

**Issue by dedemorton** [elastic/stack-docs#38]
Right now, our release notes contain a laundry list of changes. They don't do a very good job of highlighting the major changes that were added for each release. 

As a quick fix, the release notes for each product should point to the blog posts that contain the release highlights.

We should do this for all 6.x versions, and possibly 5.6.

The links need to be added to the release notes in the appropriate repo. Use this meta issue to track completion of the work:

- [ ] Elasticsearch
- [ ] Kibana
- [ ] Logstash
- [ ] Beats

**Comment by lcawl** [comment]
Note that part of the proposed changes to the release notes process has resulted in the creation of "Release Highlight" pages in the Elasticsearch Reference and Kibana Reference:
https://www.elastic.co/guide/en/elasticsearch/reference/6.3/release-highlights.html
https://www.elastic.co/guide/en/kibana/6.3/release-highlights.html
I think it seems sensible to add links to the blogs there.

**Comment by dedemorton** [comment]
Closing because we have a new strategy for providing "what's new" content about Beats (it's in the observability what's new).
