### ISSUE TITLE
Remove edit_url overrides

### ISSUE THREAD

**Issue by lcawl** [elastic/stack-docs#413]
The edit_url attributes are no longer required in the stack-docs repo and they need to be removed so that the attribute can be used in Asciidoctor builds for other books. 

- [x] master: https://github.com/elastic/stack-docs/pull/414
- [x] 7.x: https://github.com/elastic/stack-docs/pull/416
- [x] 7.3: https://github.com/elastic/stack-docs/pull/417
- [x] 7.2: https://github.com/elastic/stack-docs/pull/418
- [x] 7.1: https://github.com/elastic/stack-docs/pull/419
- [x] 7.0: https://github.com/elastic/stack-docs/pull/420
- [x] 6.8: https://github.com/elastic/stack-docs/pull/424
- [x] 6.7: https://github.com/elastic/stack-docs/commit/678e332e6b1aad0b4429a3983040826c85614834
- [x] 6.6: https://github.com/elastic/stack-docs/pull/426
- [x] 6.5: https://github.com/elastic/stack-docs/commit/b04f60ac6c6107412cd89ef0ab102cc7937013a5
- [x] 6.4: https://github.com/elastic/stack-docs/pull/427
- [x] 6.3: https://github.com/elastic/stack-docs/pull/428
~- [ ] 6.2~
~- [ ] 6.1~
~- [ ] 6.0~
~- [ ] 5.6~
~- [ ] 5.5~
~- [ ] 5.4~
~- [ ] 5.3~
~- [ ] 5.2~
~- [ ] 5.0~

Related to https://github.com/elastic/docs/pull/994

**Comment by nik9000** [comment]
:heart:
