### ISSUE TITLE
Document ML jobs built-in into SIEM

### ISSUE THREAD

**Issue by tsg** [elastic/stack-docs#472]
Since version 7.3, SIEM comes with a set of built-in jobs. 7.4 adds a few more. This ticket is about documenting the jobs: their description, what data they need, when are they useful, etc.

[Related PR](https://github.com/elastic/stack-docs/pull/509)

CC @randomuserid

**Comment by benskelker** [comment]
Opened #627 for 7.5 ML jobs but keeping this open as should backport any relevant information to the 7.4 docs.
