### ISSUE TITLE
[DOCS] Revisit Infrastructure monitoring architecture diagram and description 

### ISSUE THREAD

**Issue by Titch990** [elastic/stack-docs#480]
The component architecture diagram in this topic https://www.elastic.co/guide/en/infrastructure/guide/current/infrastructure-monitoring-overview.html needs revisiting, and considered together with similar diagrams in Uptime and APM.

- It may need to be split into two (one for Infrastructure and one for Logs).

- It refers to Infrastructure UI and Logs UI, whereas the agreed term in this context is "app" not "UI"

- It should probably be more specific about the Beats required

- It's not consistent with the equivalent diagram in APM, and the one that is soon to be added to Uptime (https://github.com/elastic/uptime/issues/57) although it may be that we decided retain some aspects of this diagram and change Uptime and/or APM for consistency. This is still to be decided.

@Titch990

**Comment by bmorelli25** [comment]
Superseded by https://github.com/elastic/observability-dev/issues/378.
