### ISSUE TITLE
Replace our GKE On-Prem docs with a link to Google's docs

### ISSUE THREAD

**Issue by DanRoscigno** [elastic/stack-docs#495]
Early this year we published an integration between Google's GKE On-Prem offering and the Elastic Stack.  Google has published the docs at their site with links to our docs and product pages.  @dedemorton and I had discussed replacing our docs with a link to Google's.

[This is where we published at elastic.co](https://www.elastic.co/guide/en/elastic-stack-gke/current/index.html)

[This is where Google has published](https://cloud.google.com/solutions/partners/monitoring-gke-on-prem-with-the-elastic-stack)

**Comment by dedemorton** [comment]
@bmorelli25 Not sure who should own this, so please feel free to re-assign. Just wanted to make sure it was on your radar after seeing Tanya's email.

**Comment by bmorelli25** [comment]
I'm not entirely sure who should own this either. It's not my wheelhouse, but it might be @Titch990s? I'll assign her for now and we can chat with @andresrc about it at our next weekly planning meeting.
