### ISSUE TITLE
Update SIEM advanced settings

### ISSUE THREAD

**Issue by benskelker** [elastic/stack-docs#511]
Need to update SIEM settings documentation on the Kabana > Management > Advanced Settings page.

**Comment by gchaps** [comment]
@benskelker The page you want to edit is here:

https://www.elastic.co/guide/en/kibana/7.3/advanced-options.html

Add the content the same way it appears in the UI.  So the SIEM section goes after the Search section.

**Comment by benskelker** [comment]
Reopening for 7.5 as UI text updated
