### ISSUE TITLE
[DOCS] Kibana Docker dev instructions is missing interpolation and has incorrect formatting

### ISSUE THREAD

**Issue by sylvie777** [elastic/stack-docs#612]
From @orhantoy (https://github.com/elastic/website-www.elastic.co/issues/4787)

Provide the following information to help us identify and troubleshoot the issue.
- Page URL: https://www.elastic.co/guide/en/kibana/current/docker.html

List out steps on how to recreate the issue.
1. `{docker-repo}:{version}` should have been interpolated with actual values. And the formatting does not match the other code blocks; it doesn't have a black background.

If you have a screenshot, add it below.

<img width="761" alt="Screenshot 2019-10-10 at 21 36 12" src="https://user-images.githubusercontent.com/809707/66600533-00153880-eba6-11e9-8507-4128026aaa57.png">

**Comment by orhantoy** [comment]
@sylvie777 This seems to have been fixed:

<img width="761" alt="Screenshot 2021-01-25 at 15 29 21" src="https://user-images.githubusercontent.com/809707/105719012-1f161600-5f22-11eb-84f9-bed3ea83fe89.png">

**Comment by sylvie777** [comment]
Excellent!
