### ISSUE TITLE
SIEM ML Jobs Documentation for 7.5

### ISSUE THREAD

**Issue by benskelker** [elastic/stack-docs#627]
Add descriptions of new jobs in 7.5 and improve the documentation of all jobs (sizing recommendations, ?manual configurations, rules, filters?, and any other relevant information).

CC @randomuserid @spong

**Comment by randomuserid** [comment]
Here's a first cut. Let's use track changes in a Gdoc to work up a draft? https://docs.google.com/document/d/1Xoc876vwEQPTUEWLWnX2kr0y5gctPAC_ugnnp7WExGY/edit
