### ISSUE TITLE
[BROKEN LINK] on "Building Queries" page

### ISSUE THREAD

**Issue by sylvie777** [elastic/stack-docs#643]
A user reported:

> On this page, https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-high-query-builders.html, the links to the API is not working. When I try to view the TermQueryBuilder class, I get a page not found. It would be great to ensure all links to documentation is maintained as it's difficult to work with the product without access to appropriate documentation. Thanks! 

cc @anaisbaccara

**Comment by jrodewig** [comment]
The link for the TermsQueryBuilder now works.  I'm closing this issue. Thanks!
