### ISSUE TITLE
[DOCS] Add page header to older versions of Infrastructure Monitoring Guide (superseded)

### ISSUE THREAD

**Issue by Titch990** [elastic/stack-docs#645]
The Infrastructure Monitoring Guide has been superseded by separate docs, Logs Monitoring guide and Metrics Monitoring Guide.

To avoid confusion, @debadair suggests adding a page header to the older documentation to refer readers to the latest documents.

Here's an example for the Elasticsearch Definitive Guide, showing how it's done: 

- https://github.com/elastic/elasticsearch-definitive-guide/blob/2.x/page_header.html
- https://www.elastic.co/guide/en/elasticsearch/guide/current/index.html

**Comment by Titch990** [comment]
Done in https://github.com/elastic/stack-docs/pull/654. Ready to merge when the 7.5 docs are released.

In the interim, while the 7.4 docs are current, but the master docs index shows the two new Logs and Metrics docs, I've also added a "future docs" banner in those docs, on Deb's advice. https://github.com/elastic/stack-docs/pull/655

That will also need to be removed when the 76.5 docs are published. https://github.com/elastic/stack-docs/pull/658

**Comment by bmorelli25** [comment]
Closed in #654
