### ISSUE TITLE
[DOCS] Minor issues in Logs installation instructions

### ISSUE THREAD

**Issue by Titch990** [elastic/stack-docs#646]
Comments from @weltenwort in review of https://github.com/elastic/stack-docs/pull/581. I've raised a separate issue because these are problems in the existing content, not problems in the split, which was the focus of the original issue.

Affected topic docs/en/logs/logs-installation.asciidoc, may also apply to closely related topic docs/en/metrics/installation.asciidoc 

> However you install {beats}, you need to enable the appropriate modules in {filebeat} to start collecting logs data

This is not necessarily true and contradicts the previous paragraph. For custom log setups users would set up the appropriate inputs and configure some processors. The modules merely provide pre-packaged sets of such configurations.

> Appropriate {beats} shippers (version 6.5 or later) installed and enabled on each system you want to . . . 

Is this guide intentionally focused on filebeat? It's possible to use other means of ingestion such as logstash and fluentd in combination with the Logs UI. Maybe this section should be called "Setting up log collection with filebeat"?

**Comment by bmorelli25** [comment]
@weltenwort, how important is this change? I'm trying to prioritize my work for 7.5.

**Comment by weltenwort** [comment]
The inaccuracies in the setup process documentation might be confusing to some users, but I can appreciate that rewriting it might be quite a bit of work. I don't have an overview of the state of the docs given the drastic changes so it's hard to judge for me. It's not really worse than what we had before, I guess.

**Comment by bmorelli25** [comment]
> It's not really worse than what we had before, I guess.

Yikes.

This is helpful, thank you.

**Comment by bmorelli25** [comment]
>  Maybe this section should be called "Setting up log collection with filebeat"?

I like this idea.

> Is this guide intentionally focused on filebeat? It's possible to use other means of ingestion such as logstash and fluentd in combination with the Logs UI.

I'm not sure that we're ready to document, in-depth, these other ingestion methods, but it might make sense to call them out and offer something to help users get started. Specifically, explaining how the apps use ECS fields would be helpful. See https://github.com/elastic/observability-dev/issues/223.
