### ISSUE TITLE
[DOCS] Logs and Metrics tasks for 7.5 release day

### ISSUE THREAD

**Issue by Titch990** [elastic/stack-docs#657]
On the 7.5 release day, the following docs changes are needed for Logs and metrics:

- [ ] Merge https://github.com/elastic/stack-docs/pull/654 into 7.4 branch (Add "superseded" banner to old Infrastructure Monitoring Guide doc)
- [ ] Backport https://github.com/elastic/stack-docs/pull/654 into all branches from 6.5 - 7.3.
- [ ] Merge PR https://github.com/elastic/stack-docs/pull/658 into master (Remove temporary "future docs" banner from 7.5 release docs). This reverts https://github.com/elastic/stack-docs/pull/655 (Adding temporary banner to mark new Logs and Metrics docs as "future").
- [ ] Backport PR #658 into 7.5 and 7.x branches.

**Comment by bmorelli25** [comment]
Consolidated into https://github.com/elastic/observability-dev/issues/428.
