### ISSUE TITLE
monitoring cluster page enhancement.

### ISSUE THREAD

**Issue by TomonoriSoejima** [elastic/stack-docs#79]
https://www.elastic.co/guide/en/elastic-stack-overview/current/monitoring-production.html

will be better if you mention adding it to elasticsearch.yml

`xpack.monitoring.collection.enabled: true`

With current instruction found on that page, it won't work as `xpack.monitoring.collection.enabled: true` is not set.

**Comment by lcawl** [comment]
That is actually the first step in https://www.elastic.co/guide/en/elasticsearch/reference/6.3/configuring-monitoring.html, which is linked in the first step in https://www.elastic.co/guide/en/elastic-stack-overview/6.3/monitoring-production.html

I realize there are a lot of little pieces that are easy to overlook in this setup. The goal is to create a "getting started" tutorial that gives a more concrete example.

**Comment by TomonoriSoejima** [comment]
Oh, thanks for pointing me to https://www.elastic.co/guide/en/elasticsearch/reference/6.3/configuring-monitoring.html. 
I must say I did not read this doc.
