### ISSUE TITLE
[Elasticsearch/ILM] Add note to ILM docs reminding use of alias

### ISSUE THREAD

**Issue by sylvie777** [elastic/stack-docs#790]
From @richiejarvis (https://github.com/elastic/website-www.elastic.co/issues/5262)

Page: https://www.elastic.co/guide/en/elasticsearch/reference/current/getting-started-index-lifecycle-management.html

SFDC Case 465423 suggests adding some text explaining that all operations should be carried out against the alias, and not the original index name for ILM to work properly.

Suggested text:

Note: In order for ILM to function correctly, all Elasticsearch interaction should now use the alias, not the original index name. In our example above, API calls should be made to datastream. Writing directly to datastream-000001 will bypass the alias, and mean that even when ILM moves the write alias, data will still be written to the wrong index.

**Comment by jrodewig** [comment]
Closing this as the default process for ILM has since changed substantially.

We now expect most users to use data stream with ILM. Data streams intentionally limit what actions can be taken on its backing indices. For example, you can't index to any backing index other than the data stream.
