### ISSUE TITLE
Document using Metricbeat for collecting and shipping monitoring metrics

### ISSUE THREAD

**Issue by lcawl** [elastic/stack-docs#86]
Related to https://github.com/elastic/beats/issues/7035

- [x] Update overview (benefits of new method) in https://www.elastic.co/guide/en/elastic-stack-overview/master/xpack-monitoring.html

- [x] Update architectural diagrams (include Metricbeat) in https://www.elastic.co/guide/en/elastic-stack-overview/master/how-monitoring-works.html See https://github.com/elastic/Design/issues/1090 and https://github.com/elastic/stack-docs/pull/125

- [x] Add new MetricBeat installation, configuration steps for Kibana data collection in https://www.elastic.co/guide/en/elastic-stack-overview/master/monitoring-production.html

- [x] Add new MetricBeat installation, configuration steps for all other products' data collection in https://www.elastic.co/guide/en/elastic-stack-overview/master/monitoring-production.html, as that functionality is enabled. 

- [x] Update the monitoring pages in the Kibana Reference to align with these changes (e.g. https://www.elastic.co/guide/en/kibana/master/monitoring-xpack-kibana.html) See https://github.com/elastic/kibana/pull/23736

- [x] Update the monitoring pages in the Elasticsearch Reference to align with these changes (e.g. https://www.elastic.co/guide/en/elasticsearch/reference/master/configuring-monitoring.html). See https://github.com/elastic/elasticsearch/pull/34339

- [ ] Update the monitoring pages in the other product references to align with these changes (e.g. https://www.elastic.co/guide/en/logstash/current/configuring-logstash.html, https://www.elastic.co/guide/en/beats/filebeat/master/monitoring.html), as that functionality is enabled.

**Comment by lcawl** [comment]
Thanks @ycombinator I've updated the beta note in master and 6.x branches via https://github.com/elastic/stack-docs/commit/fa3dd33c7f224d08e51ac956df7f4a17645811b2

Does this mean the new diagram should be retrofitted to the 6.4 branch too?

**Comment by ycombinator** [comment]
> Does this mean the new diagram should be retrofitted to the 6.4 branch too?

Yes!

**Comment by lcawl** [comment]
If more products are updated to use metricbeat for monitoring, the appropriate documentation will be updated in new PRs.
