### ISSUE TITLE
[Docs] RPM repo returning 404 errors

### ISSUE THREAD

**Issue by sylvie777** [elastic/stack-docs#956]
A web visitor submitted this message through the "Contact" page on March 26, 2020:

>Your RPM repository links at https://www.elastic.co/guide/en/elasticsearch/reference/7.6/rpm.html#rpm-repo (and prior links for 6.x and 5.x) are all returning 404 errors.

**Comment by jrodewig** [comment]
I just tested these again, and it looks like this issue has been resolved.
